### ISSUE TITLE
Consider forking three-to-ammo into c-frame

### ISSUE THREAD

**Issue by Elettrotecnica** [c-frame/aframe-physics-system#59]
Dear all,

in order to correctly compute collision shapes for models using interleaved buffer attributes, I had to massage three-to-ammo a bit: https://github.com/InfiniteLee/three-to-ammo/pull/45

The PR is open since a while and I am not sure how active the original author is. Maybe three-to-ammo should be forked in c-frame?

All the best

**Comment by diarmidmackenzie** [comment]
Hi, @Elettrotecnica, thanks for this. 

I have publishe dthe 1.0.2 version of the package here:
https://www.npmjs.com/package/@c-frame/three-to-ammo

Do you want to do a PR now to update aframe-physics-system to use that version of the package?

**Comment by Elettrotecnica** [comment]
Done! And thanks to you!
